name: 'Close Fork Pulls'
description: 'A GitHub action to close pull requests from forks'
inputs:
  token:
    description: 'GitHub auth token'
    default: ${{ github.token }}
  repository:
    description: 'The GitHub repository containing the pull request'
    default: ${{ github.repository }}
  comment:
    description: 'A comment to make on the pull requests before closing'
  pr-number:
    description: 'Target PR number'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'slash'
  color: 'gray-dark'
